-   id: pyupgrade-opt
    name: pyupgrade-opt
    description: Automatically upgrade syntax for newer versions of Python.
    entry: pyupgrade-opt
    language: python
    types: [python]
    # for backward compatibility
    files: ''
    minimum_pre_commit_version: 0.15.0
