-   id: pyupgrade
    name: pyupgrade
    description: Automatically upgrade syntax for newer versions.
    entry: pyupgrade
    language: python
    types: [python]
    # for backward compatibility
    files: ''
    minimum_pre_commit_version: 0.15.0
